version: "2.3"
services:
  nwnserver:
    image: nwnxee/nwserver:8162
    ports:
      - "5121:5121/udp"
    links:
      - "db:db"
    tty: true
    environment:
      NWN_PORT: 5121
      NWN_MODULE: 
      NWN_SERVERNAME: 
      NWN_PUBLICSERVER: 1
      NWN_MAXCLIENTS: 96
      NWN_MINLEVEL: 1
      NWN_MAXLEVEL: 40
      NWN_PAUSEANDPLAY: 0
      NWN_PVP: 2
      NWN_SERVERVAULT: 1
      NWN_ELC: 1
      NWN_ILR: 1
      NWN_GAMETYPE: 0
      NWN_ONEPARTY: 1
      NWN_DIFFICULTY: 3
      NWN_AUTOSAVEINTERVAL: 0
      NWN_RELOADWHENEMPTY: 0
      NWN_PLAYERPASSWORD: 
      NWN_DMPASSWORD: 
      NWN_ADMINPASSWORD: 
      NWNX_ADMINISTRATION_SKIP: y
      NWNX_BEHAVIOURTREE_SKIP: y
      NWNX_CHAT_SKIP: y
      NWNX_CREATURE_SKIP: y
      NWNX_EVENTS_SKIP: y
      NWNX_DATA_SKIP: y
      NWNX_METRICS_INFLUXDB_SKIP: y
      NWNX_OBJECT_SKIP: y
      NWNX_PLAYER_SKIP: y
      NWNX_RUBY_SKIP: y
      NWNX_SERVERLOGREDIRECTOR_SKIP: n
      NWNX_SQL_SKIP: n
      NWNX_THREADWATCHDOG_SKIP: y
      NWNX_TRACKING_SKIP: y
      # Configure DB
      NWNX_SQL_TYPE: MYSQL
      NWNX_SQL_HOST: db
      NWNX_SQL_USERNAME: 
      NWNX_SQL_PASSWORD: 
      NWNX_SQL_DATABASE: 
    volumes:
      - .:/nwn/home
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:10.2.13
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      # Update the password below
      test: ["CMD", "mysqladmin", "-p<replace with admin password>", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 5s
    environment:
      # Configure DB
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    volumes:
      - ./mysql:/var/lib/mysql